---
resources:
  - name: compose-sample-git
    type: git
    source:
      uri: https://github.com/miccheng/concourse-docker-compose-sample.git
      branch: master

jobs:
  - name: compose-sample
    plan:
    - get: compose-sample-git
      trigger: true

    - task: spec
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: pivotalsingapore/docker-docker-compose
        inputs:
          - name: compose-sample-git
        run:
          path: compose-sample-git/run-test-in-concourse.sh
